<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Package;
use App\Models\Category;
use Illuminate\Support\Facades\DB;

class PackageSeeder extends Seeder
{
    public function run(): void
    {
        // Nonaktifkan pengecekan foreign key
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Hapus data lama (sekarang diizinkan)
        DB::table('packages')->truncate();

        // Aktifkan kembali pengecekan foreign key
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Ambil semua kategori untuk digunakan dalam seeding
        $categories = Category::all();

        // Data dummy packages
        $packages = [
            // ===========================
            // PAKET 1 – UMROH
            // ===========================
             [
                'name' => 'Paket Umroh Akhir Tahun 2025 14 Hari',
                'slug' => 'paket-umroh-akhir-tahun-2025-14-hari-1',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 31550000,
                'departure_date' => '2025-12-03',
                'duration_days' => 14,
                'airline' => 'Garuda Indonesia',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh1.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => true,
                'description' => 'Paket Umroh Akhir Tahun 2025 selama 14 hari dengan fasilitas lengkap dan pelayanan terbaik.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Akhir Tahun 2025 12 Hari',
                'slug' => 'paket-umroh-akhir-tahun-2025-12-hari-7desember',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 31500000,
                'departure_date' => '2025-12-07',
                'duration_days' => 12,
                'airline' => 'Garuda Indonesia',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh2.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Akhir Tahun 2025 selama 12 hari...',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah\nMuthawif\nAsuransi",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Akhir Tahun 2025 9 Hari',
                'slug' => 'paket-umroh-akhir-tahun-2025-9-hari-3',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 35050000,
                'departure_date' => '2025-12-09',
                'duration_days' => 9,
                'airline' => 'Garuda Indonesia',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh3.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Akhir Tahun 2025 selama 9 hari dengan akomodasi nyaman dan layanan terpercaya.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Akhir Tahun 2025 16 Hari',
                'slug' => 'paket-umroh-akhir-tahun-2025-16-hari-4',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 30550000,
                'departure_date' => '2025-12-10',
                'duration_days' => 16,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh4.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Akhir Tahun 2025 selama 16 hari menggunakan Lion Air dengan fasilitas lengkap.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Akhir Tahun 2025 16 Hari',
                'slug' => 'paket-umroh-akhir-tahun-2025-16-hari-5',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 42500000,
                'departure_date' => '2025-12-13',
                'duration_days' => 16,
                'airline' => 'Garuda Indonesia',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh5.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Akhir Tahun 2025 selama 16 hari dengan fasilitas premium dan kenyamanan terbaik.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Akhir Tahun 2025 12 Hari',
                'slug' => 'paket-umroh-akhir-tahun-2025-12-hari-13desember',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 30500000,
                'departure_date' => '2025-12-13',
                'duration_days' => 12,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh7.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Akhir Tahun 2025 selama 12 hari dengan pelayanan profesional, menggunakan maskapai Lion Air.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Akhir Tahun 2025 12 Hari',
                'slug' => 'paket-umroh-akhir-tahun-2025-12-hari-14desember',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 34700000,
                'departure_date' => '2025-12-14',
                'duration_days' => 12,
                'airline' => 'Garuda Indonesia',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh8.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh 12 Hari dengan kenyamanan lebih menggunakan Garuda Indonesia.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Akhir Tahun 2025 9 Hari',
                'slug' => 'paket-umroh-akhir-tahun-2025-9-hari-8',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 28700000,
                'departure_date' => '2025-12-16',
                'duration_days' => 9,
                'airline' => 'Garuda Indonesia',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh9.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh hemat 9 hari dengan maskapai Garuda Indonesia dan fasilitas nyaman.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Akhir Tahun 2025 16 Hari',
                'slug' => 'paket-umroh-akhir-tahun-2025-16-hari-9',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 34500000,
                'departure_date' => '2025-12-20',
                'duration_days' => 16,
                'airline' => 'Garuda Indonesia',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh10.jpeg',
                'total_seats' => 45,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh 16 hari dengan layanan lengkap dan kenyamanan maksimal menggunakan Garuda Indonesia.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Akhir Tahun 2025 12 Hari',
                'slug' => 'paket-umroh-akhir-tahun-2025-12-hari-20desember',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 37500000,
                'departure_date' => '2025-12-20',
                'duration_days' => 12,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh11.jpeg',
                'total_seats' => 45,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh 12 hari akhir tahun dengan harga kompetitif dan fasilitas lengkap menggunakan Lion Air.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Akhir Tahun 2025 12 Hari',
                'slug' => 'paket-umroh-akhir-tahun-2025-12-hari-11',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 31350000,
                'departure_date' => '2025-12-25',
                'duration_days' => 12,
                'airline' => 'Garuda Indonesia',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh12.jpeg',
                'total_seats' => 45,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh 12 hari akhir tahun dengan fasilitas lengkap bersama Garuda Indonesia.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Akhir Tahun 2025 16 Hari',
                'slug' => 'paket-umroh-akhir-tahun-2025-16-hari-11',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 32000000,
                'departure_date' => '2025-12-27',
                'duration_days' => 16,
                'airline' => 'Garuda Indonesia',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh13.jpeg',
                'total_seats' => 45,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh 16 hari akhir tahun dengan fasilitas premium bersama Garuda Indonesia.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Lengkap Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Awal Tahun 2026 12 Hari',
                'slug' => 'paket-umroh-awal-tahun-2026-12-hari-12',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 32000000,
                'departure_date' => '2026-01-01',
                'duration_days' => 12,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh14.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh awal tahun 2026 selama 12 hari dengan harga ekonomis.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Awal Tahun 2026 13 Hari',
                'slug' => 'paket-umroh-awal-tahun-2026-13-hari-13',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 32500000,
                'departure_date' => '2026-01-07',
                'duration_days' => 13,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh15.jpeg',
                'total_seats' => 30,     // Kamu tampilkan sisa 6 → berarti total 30
                'seats_filled' => 24,    // 80% terisi
                'is_featured' => false,
                'description' => 'Paket Umroh awal tahun 2026 selama 13 hari dengan keberangkatan dari Juanda.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Lengkap\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Awal Tahun 2026 12 Hari',
                'slug' => 'paket-umroh-awal-tahun-2026-12-hari-14',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 32000000,
                'departure_date' => '2026-01-12',
                'duration_days' => 12,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh16.jpeg',
                'total_seats' => 25,     // Kamu tampilkan sisa 10 → berarti total 25
                'seats_filled' => 15,    // 60% terisi
                'is_featured' => false,
                'description' => 'Paket Umroh awal tahun 2026 12 hari dengan fasilitas lengkap dan harga terbaik.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Awal Tahun 2026 16 Hari',
                'slug' => 'paket-umroh-awal-tahun-2026-16-hari-15',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 32000000,
                'departure_date' => '2026-01-17',
                'duration_days' => 16,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh17.jpeg',
                'total_seats' => 25,     // 60% terisi → sisa 10 → total 25
                'seats_filled' => 15,
                'is_featured' => false,
                'description' => 'Paket Umroh 16 hari awal tahun 2026 dengan fasilitas lengkap dan pelayanan terbaik.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Lengkap\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Awal Tahun 2026 16 Hari',
                'slug' => 'paket-umroh-awal-tahun-2026-16-hari-16',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 33550000,
                'departure_date' => '2026-01-24',
                'duration_days' => 16,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh18.jpeg',
                'total_seats' => 25,    // 60% terisi → sisa 10 → total 25
                'seats_filled' => 15,
                'is_featured' => false,
                'description' => 'Paket Umroh 16 hari awal tahun 2026 dengan harga terjangkau dan fasilitas nyaman.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Lengkap\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Awal Tahun 2026 12 Hari',
                'slug' => 'paket-umroh-awal-tahun-2026-12-hari-17',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 32500000,
                'departure_date' => '2026-02-01',
                'duration_days' => 12,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh19.jpeg',
                'total_seats' => 25,     // 60% terisi → sisa 10 → total 25
                'seats_filled' => 15,
                'is_featured' => false,
                'description' => 'Paket Umroh 12 hari awal Februari 2026 dengan pelayanan nyaman dan harga terbaik.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Awal Tahun 2026 13 Hari',
                'slug' => 'paket-umroh-awal-tahun-2026-13-hari-18',
                'category_id' => $categories->where('slug', 'umrah')->first()->id ?? 1,
                'price' => 32500000,
                'departure_date' => '2026-02-03',
                'duration_days' => 13,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/umroh/umroh20.jpeg',
                'total_seats' => 30,     // sisa 6 → terisi 80% → total 30
                'seats_filled' => 24,
                'is_featured' => false,
                'description' => 'Paket Umroh 13 hari awal Februari 2026 dengan fasilitas lengkap dan harga terjangkau.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Lengkap\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Awal Tahun 2026 16 Hari',
                'slug' => 'paket-umroh-awal-tahun-2026-16-hari-18',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 3,
                'price' => 33500000,
                'departure_date' => '2026-02-07',
                'duration_days' => 16,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh21.jpeg',
                'total_seats' => 25,
                'seats_filled' => 15,
                'is_featured' => false,
                'description' => 'Paket Umroh awal tahun 2026 selama 16 hari dengan fasilitas lengkap dan perjalanan nyaman.',
                'include_items' => "Durasi: 16 Hari\nMaskapai: Lion-air\nHotel Makkah: Hotel Makkah\nHotel Madinah: Hotel Madinah",
                'exclude_items' => null,
            ],
            [
                'name' => 'Paket Umroh Awal Tahun 2026 12 Hari',
                'slug' => 'paket-umroh-awal-tahun-2026-12-hari-19',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 3,
                'price' => 32000000,
                'departure_date' => '2026-02-08',
                'duration_days' => 12,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh22.jpeg',
                'total_seats' => 25,
                'seats_filled' => 15,
                'is_featured' => false,
                'description' => 'Paket Umroh awal tahun 2026 selama 12 hari dengan fasilitas lengkap.',
                'include_items' => "Durasi: 12 Hari\nMaskapai: Lion-air\nHotel Makkah: Hotel Makkah\nHotel Madinah: Hotel Madinah",
                'exclude_items' => null,
            ],
            [
                'name' => 'Paket Umroh Awal Tahun 2026 16 Hari',
                'slug' => 'paket-umroh-awal-tahun-2026-16-hari-20',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 3,
                'price' => 32000000,
                'departure_date' => '2026-02-14',
                'duration_days' => 16,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh23.jpeg',
                'total_seats' => 25,
                'seats_filled' => 15,
                'is_featured' => false,
                'description' => 'Paket Umroh awal tahun 2026 selama 16 hari dengan fasilitas lengkap.',
                'include_items' => "Durasi: 16 Hari\nMaskapai: Lion-air\nHotel Makkah: Hotel Makkah\nHotel Madinah: Hotel Madinah",
                'exclude_items' => null,
            ],
            [
                'name' => 'Paket Umroh Awal Tahun 2026 16 Hari',
                'slug' => 'paket-umroh-awal-tahun-2026-16-hari-21',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 3,
                'price' => 32000000,
                'departure_date' => '2026-02-14',
                'duration_days' => 16,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh23.jpeg',
                'total_seats' => 25,
                'seats_filled' => 15,
                'is_featured' => false,
                'description' => 'Paket Umroh awal tahun 2026 selama 16 hari dengan fasilitas lengkap.',
                'include_items' => "Durasi: 16 Hari\nMaskapai: Lion-air\nHotel Makkah: Hotel Makkah\nHotel Madinah: Hotel Madinah",
                'exclude_items' => null,
            ],
            [
                'name' => 'Paket Umroh Full Ramadhan 2026',
                'slug' => 'paket-umroh-full-ramadhan-2026-22',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 3,
                'price' => 44500000,
                'departure_date' => '2026-02-22',
                'duration_days' => null,
                'airline' => 'Lion-air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umrohfull ramadhan.jpeg',
                'total_seats' => 20,
                'seats_filled' => 10,
                'is_featured' => true,
                'description' => 'Paket Umroh Full Ramadhan 2026 dengan fasilitas premium dan pengalaman ibadah maksimal di bulan suci.',
                'include_items' => "Maskapai: Lion-air\nHotel Makkah: Hotel Makkah\nHotel Madinah: Hotel Madinah",
                'exclude_items' => null,
            ],
            [
                'name' => 'Paket Umroh Ramadhan 2026 12 Hari',
                'slug' => 'paket-umroh-ramadhan-2026-12-hari-23',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 35800000,
                'departure_date' => '2026-02-15',
                'duration_days' => 12,
                'airline' => 'Lion Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh24.jpeg',
                'total_seats' => 40,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Ramadhan 2026 selama 12 hari dengan keberangkatan 15 Februari 2026 menggunakan Lion Air.',
                'include_items' => null,
                'exclude_items' => null,
            ],
            [
                'name' => 'Paket Umroh Ramadhan 2026 12 Hari',
                'slug' => 'paket-umroh-ramadhan-2026-12-hari-24',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 34950000,
                'departure_date' => '2026-02-15',
                'duration_days' => 12,
                'airline' => 'Lion Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh25.jpeg',
                'total_seats' => 40,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Ramadhan 2026 selama 12 hari dengan keberangkatan 15 Februari 2026 menggunakan Lion Air.',
                'include_items' => null,
                'exclude_items' => null,
            ],
            [
                'name' => 'Paket Umroh Ramadhan 2026 13 Hari',
                'slug' => 'paket-umroh-ramadhan-2026-13-hari-25',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 36550000,
                'departure_date' => '2026-02-09',
                'duration_days' => 13,
                'airline' => 'Lion Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh26.jpeg',
                'total_seats' => 40,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Ramadhan 2026 selama 13 hari dengan keberangkatan 9 Februari 2026 menggunakan Lion Air.',
                'include_items' => null,
                'exclude_items' => null,
            ],
            [
                'name' => 'Paket Umroh Ramadhan 2026 16 Hari',
                'slug' => 'paket-umroh-ramadhan-2026-16-hari-26',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 38350000,
                'departure_date' => '2026-02-10',
                'duration_days' => 16,
                'airline' => 'Lion Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh27.jpeg',
                'total_seats' => 40,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Ramadhan 2026 selama 16 hari dengan keberangkatan 10 Februari 2026 menggunakan Lion Air.',
                'include_items' => null,
                'exclude_items' => null,
            ],
            [
                'name' => 'Paket Umroh Ramadhan 2026 16 Hari',
                'slug' => 'paket-umroh-ramadhan-2026-16-hari-27',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 40150000,
                'departure_date' => '2026-02-07',
                'duration_days' => 16,
                'airline' => 'Lion Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh28.jpeg',
                'total_seats' => 40,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Ramadhan 2026 selama 16 hari dengan keberangkatan 7 Februari 2026 menggunakan Lion Air.',
                'include_items' => null,
                'exclude_items' => null,
            ],
            [
                'name' => 'Paket Umroh Ramadhan 2026 16 Hari',
                'slug' => 'paket-umroh-ramadhan-2026-16-hari-28',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 38150000,
                'departure_date' => '2026-02-07',
                'duration_days' => 16,
                'airline' => 'Lion Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh29.jpeg',
                'total_seats' => 40,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Ramadhan 2026 selama 16 hari keberangkatan 7 Februari 2026 dengan Lion Air.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Ramadhan 2026 16 Hari',
                'slug' => 'paket-umroh-ramadhan-2026-16-hari-29',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 37500000,
                'departure_date' => '2026-02-08',
                'duration_days' => 16,
                'airline' => 'Lion Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh30.jpeg',
                'total_seats' => 40,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Ramadhan 2026 selama 16 hari keberangkatan 8 Februari 2026 dengan Lion Air.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Ramadhan 2026 30 Hari',
                'slug' => 'paket-umroh-ramadhan-2026-30-hari-30',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 52500000,
                'departure_date' => '2026-02-25',
                'duration_days' => 30,
                'airline' => 'Lion Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh31.jpeg',
                'total_seats' => 40,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Ramadhan 2026 selama 30 hari keberangkatan 25 Februari 2026 dengan Lion Air.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Ramadhan 2026 30 Hari',
                'slug' => 'paket-umroh-ramadhan-2026-30-hari-31',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 49500000,
                'departure_date' => '2026-02-25',
                'duration_days' => 30,
                'airline' => 'Lion Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh32.jpeg',
                'total_seats' => 40,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Ramadhan 2026 selama 30 hari keberangkatan 25 Februari 2026 menggunakan Lion Air.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Ramadhan 2026 16 Hari',
                'slug' => 'paket-umroh-ramadhan-2026-16-hari-32',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 44350000,
                'departure_date' => '2026-03-07',
                'duration_days' => 16,
                'airline' => 'Lion Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh33.jpeg',
                'total_seats' => 40,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Ramadhan 2026 selama 16 hari keberangkatan 7 Maret 2026 dengan Lion Air.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Ramadhan 2026 16 Hari',
                'slug' => 'paket-umroh-ramadhan-2026-16-hari-33',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 51650000,
                'departure_date' => '2026-03-07',
                'duration_days' => 16,
                'airline' => 'Lion Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umroh34',
                'total_seats' => 40,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Ramadhan 2026 selama 16 hari keberangkatan 7 Maret 2026 menggunakan Lion Air.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Akhir Ramadhan 2026 16 Hari',
                'slug' => 'paket-umroh-akhir-ramadhan-2026-16-hari-34',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 41500000,
                'departure_date' => '2026-04-01',
                'duration_days' => 16,
                'airline' => 'Lion Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umrohakhirramadhan.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Akhir Ramadhan 2026 selama 16 hari keberangkatan tahun 2026 dengan Lion Air.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Plus Dubai 10 Hari',
                'slug' => 'paket-umroh-plus-dubai-10-hari-35',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 30500000,
                'departure_date' => '2025-11-12',
                'duration_days' => 10,
                'airline' => 'Emirates',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umrohdubai.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Plus Dubai 10 hari dengan keberangkatan 12 November 2025 menggunakan Emirates.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Plus Turki 12 Hari',
                'slug' => 'paket-umroh-plus-turki-12-hari-36',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 48900000,
                'departure_date' => '2025-12-24',
                'duration_days' => 12,
                'airline' => 'Saudia - Turkish Airlines',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umrohturki.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Plus Turki 12 hari dengan keberangkatan 24 Desember 2025 menggunakan Saudia dan Turkish Airlines.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Plus Al-Aqsha 13 Hari',
                'slug' => 'paket-umroh-plus-al-aqsha-13-hari-37',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 2,
                'price' => 73541600,
                'departure_date' => '2025-11-01',
                'duration_days' => 13,
                'airline' => 'Oman Air',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'image_url' => 'assets/img/umroh/umrohalaqhsa.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Plus Al-Aqsha 13 hari keberangkatan November 2025 menggunakan Oman Air.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nZiarah Makkah & Madinah\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi",
            ],      
            // ===========================
            // PAKET 2 – HAJI
            // ===========================
            [
                'name' => 'Paket Haji VIP 2026',
                'slug' => 'paket-haji-vip-2026-38',
                'category_id' => $categories->where('slug', 'haji')->first()->id ?? 2,
                'price' => 340000000,
                'departure_date' => '2025-12-20',
                'duration_days' => 27,
                'airline' => 'Garuda',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/haji/BROSUR HAJI 2026 VIP.jpg',
                'total_seats' => 40,
                'seats_filled' => 37, // 3 seat tersisa
                'is_featured' => true,
                'description' => 'Paket Haji VIP 2026 selama 27 hari dengan pelayanan premium, hotel dekat Masjidil Haram dan Masjid Nabawi, serta fasilitas eksklusif lainnya.',
                'include_items' => "Tiket Pesawat PP\nHotel Makkah & Madinah\nTransportasi Bus AC\nMakan 3x Sehari\nManasik Haji\nMuthawif Berpengalaman\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin Meningitis\nKeperluan Pribadi\nKelebihan Bagasi\nTour di Luar Program",
            ],
            // ===========================
            // PAKET 2 – HAJI REGULER 2026
            // ===========================
            [
                'name' => 'Paket Haji Reguler 2026',
                'slug' => 'paket-haji-reguler-2026-39',
                'category_id' => $categories->where('slug', 'haji')->first()->id ?? 2,
                'price' => 280000000,
                'departure_date' => '2026-01-10',
                'duration_days' => 27,
                'airline' => 'Qatar Airways',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => null,
                'image_url' => 'assets/img/haji/BROSUR HAJI 2026.jpg',
                'total_seats' => 30,
                'seats_filled' => 24, // 80% terisi (6 seat tersisa)
                'is_featured' => false,
                'description' => 'Paket Haji Reguler 2026 selama 27 hari dengan fasilitas hotel Makkah dan Madinah yang nyaman serta layanan haji profesional.',
                'include_items' => "Tiket Pesawat PP\nAkomodasi Hotel\nTransportasi Bus AC\nMakan 3x Sehari\nManasik Haji\nMuthawif\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVaksin\nKeperluan Pribadi\nTour Tambahan\nKelebihan Bagasi",
            ],
            [
                'name' => 'Paket Umroh Plus Dubai 10 Hari',
                'slug' => 'paket-umroh-plus-dubai-10-hari-40',
                'category_id' => $categories->where('slug', 'umroh')->first()->id ?? 3,
                'price' => 30500000,
                'departure_date' => '2025-11-12',
                'duration_days' => 10,
                'airline' => 'Emirates',
                'departure_city' => 'Juanda (SUB)',
                'hotel_makkah' => 'Hotel Makkah',
                'hotel_madinah' => 'Hotel Madinah',
                'other_hotels' => 'Hotel Dubai',
                'image_url' => 'assets/img/umroh/umrohdubai.jpeg',
                'total_seats' => 35,
                'seats_filled' => 0,
                'is_featured' => false,
                'description' => 'Paket Umroh Plus Dubai selama 10 hari dengan penerbangan Emirates, mengunjungi Dubai sebelum menjalankan ibadah umroh di Tanah Suci.',
                'include_items' => "Tiket Pesawat PP\nAkomodasi Hotel Makkah & Madinah\nCity Tour Dubai\nMakan 3x Sehari\nTransportasi Bus AC\nPembimbing Ibadah\nVisa Umroh\nHandling Bandara",
                'exclude_items' => "Passport\nKeperluan Pribadi\nKelebihan Bagasi\nVaksin Meningitis\nTour Tambahan Dubai\nTip Guide",
            ],                
            [
                'name' => 'Wisata Religi Turki',
                'slug' => 'wisata-religi-turki',
                'category_id' => $categories->where('slug', 'wisata-religi')->first()->id ?? 4,
                'price' => 25000000,
                'departure_date' => null, // Field ini sekarang bisa null sesuai migration
                'duration_days' => null, // Field ini sekarang bisa null sesuai migration
                'airline' => null, // Field ini sekarang bisa null sesuai migration
                'departure_city' => null, // Field ini sekarang bisa null sesuai migration
                'hotel_makkah' => null, // Tidak relevan untuk wisata religi
                'hotel_madinah' => null, // Tidak relevan untuk wisata religi
                'other_hotels' => 'Hotel di Istanbul, Ankara, dan Cappadocia',
                'image_url' => 'assets/img/galery/turki 4.jpeg',
                'total_seats' => null, // Field ini sekarang bisa null sesuai migration
                'seats_filled' => null, // Field ini sekarang bisa null sesuai migration
                'is_featured' => false,
                'description' => 'Wisata religi ke negara muslim Turki dengan mengunjungi tempat-tempat bersejarah dan religius seperti Aya Sofya, Masjid Biru, dan Cappadocia.',
                'include_items' => "Tiket Pesawat PP\nAkomodasi Hotel\nTransportasi Wisata\nTour Guide Lokal\nMakan 2x Sehari\nTiket Masuk Objek Wisata\nAsuransi Perjalanan",
                'exclude_items' => "Passport\nVisa Turki\nKeperluan Pribadi\nTour di luar program\nKelebihan bagasi\nTiket domestik\nTip Guide",
            ],
            [
                'name' => 'Pembuatan Visa',
                'slug' => 'pembuatan-visa',
                'category_id' => $categories->where('slug', 'produk-lain')->first()->id ?? 4,
                'price' => 1500000,
                'departure_date' => null,
                'duration_days' => null,
                'airline' => null,
                'departure_city' => null,
                'hotel_makkah' => null,
                'hotel_madinah' => null,
                'other_hotels' => null,
                'image_url' => 'assets/img/produk/visa.jpg',
                'total_seats' => null,
                'seats_filled' => null,
                'is_featured' => false,
                'description' => 'Layanan pembuatan visa Umroh, Haji, dan Kunjungan dengan proses cepat 3–7 hari kerja.',
                'include_items' => "Jenis Visa: Umroh, Haji, & Kunjungan\nProses: 3–7 Hari Kerja\nDokumen: Paspor, Foto, KTP\nBantuan penuh selama proses pengajuan",
                'exclude_items' => null,
            ]
            
        ];

        // Buat data packages
        foreach ($packages as $packageData) {
            Package::create($packageData);
        }
    }
}
